site_name: "Archan"
site_description: "Analysis of your architecture strength based on DSM data."
site_url: "https://pawamoy.github.io/archan"
repo_url: "https://github.com/pawamoy/archan"
repo_name: "pawamoy/archan"
site_dir: "site"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Code Reference:
  - analysis.py: reference/analysis.md
  - cli.py: reference/cli.md
  - config.py: reference/config.md
  - dsm.py: reference/dsm.md
  - enums.py: reference/enums.md
  - errors.py: reference/errors.md
  - logging.py: reference/logging.md
  - plugins:
      - checkers.py: reference/plugins/checkers.md
      - providers.py: reference/plugins/providers.md
  - printing.py: reference/printing.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    watch:
    - src/archan
- macros:
    module_name: docs/macros
