name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  PYTHONIOENCODING: "UTF-8"

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: quality-venv-cache

    - name: Set up the project
      run: |
        pip install poetry
        poetry install -v || { rm -rf .venv; poetry install -v; }
        poetry update

    - name: Check if the documentation builds correctly
      run: poetry run duty check-docs

    - name: Check the code quality
      run: poetry run duty check-code-quality

    - name: Check if the code is correctly typed
      run: poetry run duty check-types

    - name: Check for vulnerabilities in dependencies
      run: |
        pip install safety
        poetry run duty check-dependencies

  tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: tests-venv-cache-${{ matrix.os }}-py${{ matrix.python-version }}

    - name: Set up the project
      run: |
        pip install poetry
        poetry install -v || { rm -rf .venv; poetry install -v; }
        poetry update

    - name: Run the test suite
      run: poetry run duty test
