name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: 3.8

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: checks-cache

    - name: Resolving dependencies
      run: |
        pdm info
        pdm lock
